import datetime

# Colors
PRIMARY_COLOR = "#ff4b4b"
SELECTED_PRIMARY_COLOR = "#b83232"

# Sector tickers
FINANCE_TICKERS = ["JPM", "BAC", "GS", "MS", "WFC"]
HEALTHCARE_TICKERS = ["JNJ", "PFE", "MRK", "UNH", "ABBV"]
TECH_TICKERS = ["AAPL", "MSFT", "GOOGL", "AMZN", "META"]
ENERGY_TICKERS = ["DUK", "SO", "D", "NEE", "AEP"]

# Combined tickers
ALL_TICKERS = FINANCE_TICKERS + HEALTHCARE_TICKERS + TECH_TICKERS + ENERGY_TICKERS

# Default tickers
DEFAULT_TICKERS_LIST = TECH_TICKERS
TICKERS_SELECTION_COLORS = {ticker: PRIMARY_COLOR for ticker in DEFAULT_TICKERS_LIST}

# Default dates
DEFAULT_START_DATE = "2016-01-04"
DEFAULT_END_DATE = datetime.datetime.today().strftime("%Y-%m-%d") 

# Paths
DATA_FOLDER_PATH = "data"